version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENV=development
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

