services:
  web:
    build: .
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /app
          action: sync
    env_file:
      - .env
    environment:
      - ENV=development
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"